version: '3'
services:

  cluster0-0:
    image: mongo:latest
    command: mongod --replSet cluster0 --smallfiles
  cluster0-1:
    image: mongo:latest
    command: mongod --replSet cluster0 --smallfiles
  cluster0-2:
    image: mongo:latest
    command: mongod --replSet cluster0 --smallfiles

  setup:
    image: mongo:latest
    depends_on:
      - cluster0-0
      - cluster0-1
      - cluster0-2
    volumes:
    - $PWD/scripts/setup:/setup
    entrypoint: /setup/entrypoint.sh
    links:
      - cluster0-0:cluster0-0
      - cluster0-1:cluster0-1
      - cluster0-2:cluster0-2
