version: '3'
services:

  config0:
    image: mongo:latest
    command: mongod --replSet config --configsvr
    links:
    - cluster0-shard0-0:cluster0-shard0-0
    - cluster1-shard0-0:cluster1-shard0-0
  config1:
    image: mongo:latest
    command: mongod --replSet config --configsvr
    links:
    - cluster0-shard0-0:cluster0-shard0-0
    - cluster1-shard0-0:cluster1-shard0-0

  cluster0-shard0-0:
    image: mongo:latest
    command: mongod --replSet cluster0-shard0 --shardsvr --smallfiles
  cluster0-shard0-1:
    image: mongo:latest
    command: mongod --replSet cluster0-shard0 --shardsvr --smallfiles
  cluster0-shard0-2:
    image: mongo:latest
    command: mongod --replSet cluster0-shard0 --shardsvr --smallfiles

  cluster1-shard0-0:
    image: mongo:latest
    command: mongod --replSet cluster1-shard0 --shardsvr --smallfiles
  cluster1-shard0-1:
    image: mongo:latest
    command: mongod --replSet cluster1-shard0 --shardsvr --smallfiles
  cluster1-shard0-2:
    image: mongo:latest
    command: mongod --replSet cluster1-shard0 --shardsvr --smallfiles

  mongos:
    image: mongo:latest
    depends_on:
    - config0
    - config1
    command: mongos --configdb config/config0,config1 --bind_ip_all
    links:
    - config0:config0
    - config1:config1

  setup:
    image: mongo:latest
    depends_on:
    - config0
    - config1
    - mongos
    - cluster0-shard0-0
    - cluster0-shard0-1
    - cluster0-shard0-2
    - cluster1-shard0-0
    - cluster1-shard0-1
    - cluster1-shard0-2
    volumes:
    - $PWD/scripts/setup:/setup
    entrypoint: /setup/entrypoint.sh
    links:
    - config0:config0
    - config1:config1
    - mongos:mongos
    - cluster0-shard0-0:cluster0-shard0-0
    - cluster0-shard0-1:cluster0-shard0-1
    - cluster0-shard0-2:cluster0-shard0-2
    - cluster1-shard0-0:cluster1-shard0-0
    - cluster1-shard0-1:cluster1-shard0-1
    - cluster1-shard0-2:cluster1-shard0-2
  