version: '3'
services:

  cluster0-0:
    image: mongo:latest
    command: mongod --replSet cluster0 --smallfiles
    ports:
    - 27017:27017
  cluster0-1:
    image: mongo:latest
    command: mongod --replSet cluster0 --smallfiles
    ports:
    - 27018:27017
  cluster0-2:
    image: mongo:latest
    command: mongod --replSet cluster0 --smallfiles
    ports:
    - 27019:27017

  setup:
    image: mongo:latest
    depends_on:
      - cluster0-0
      - cluster0-1
      - cluster0-2
    volumes:
    - $PWD/docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: /docker-entrypoint.sh